#!/usr/bin/env python3
"""Analyze narration into rule-based director decisions."""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parents[2]
CURRENT_DIR = Path(__file__).resolve().parent
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))
if str(CURRENT_DIR) not in sys.path:
    sys.path.insert(0, str(CURRENT_DIR))

from apps.common.project_config import get_nested, load_project_config  # noqa: E402
from adventure_dna import apply_adventure_dna, load_adventure_dna  # noqa: E402

EMOTION_KEYWORDS = {
    "awe": ["마침내", "거대한", "우주", "깊은", "경이", "솟아", "심장"],
    "isolation": ["아무것도", "끝", "작은", "혼자", "고요", "비어", "멀리"],
    "discovery": ["나타난다", "발견", "드러", "처음", "도착", "색이"],
    "tension": ["전", "기다", "낮아", "너머", "마지막"],
    "memory": ["기억", "시간", "일억", "한때", "화폐", "지층"],
}

VISUAL_KEYWORDS = {
    "drone-wide": ["거대한", "대지", "계곡", "산", "솟는다", "우주"],
    "drone-reveal": ["나타난다", "드러", "마침내", "도착", "끝"],
    "detail-texture": ["층", "결", "분필", "철분", "색", "지층"],
    "human-scale": ["사람", "작은", "앉은", "트래킹", "텐트"],
    "night-sky": ["은하수", "달", "밤", "우주"],
}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Analyze narration into director decisions")
    parser.add_argument("--project-folder", required=True, help="Project folder containing project.yaml")
    return parser.parse_args()


def read_narration(config: dict[str, Any]) -> list[str]:
    path_value = get_nested(config, "paths.narration")
    if not path_value:
        return []
    path = Path(str(path_value)).expanduser()
    if not path.exists():
        return []

    text = path.read_text(encoding="utf-8")
    lines = []
    for raw in text.splitlines():
        line = raw.strip()
        if not line or line.startswith("#") or line.startswith("```"):
            continue
        if line.startswith("[") and "]" in line:
            line = re.sub(r"^\[[^\]]+\]\s*", "", line).strip()
        if line:
            lines.append(line)
    return lines


def score_keywords(text: str, keyword_map: dict[str, list[str]]) -> dict[str, int]:
    scores = {key: 0 for key in keyword_map}
    for key, words in keyword_map.items():
        for word in words:
            if word in text:
                scores[key] += 1
    return scores


def top_key(scores: dict[str, int], fallback: str) -> str:
    ranked = sorted(scores.items(), key=lambda item: item[1], reverse=True)
    if not ranked or ranked[0][1] == 0:
        return fallback
    return ranked[0][0]


def rhythm_for_text(text: str) -> str:
    length = len(text)
    if length < 30:
        return "slow-hold"
    if length < 80:
        return "measured"
    return "flowing"


def silence_need(emotion: str, text: str) -> str:
    if emotion in {"awe", "isolation"}:
        return "high"
    if "그리고" in text or "마침내" in text:
        return "medium"
    return "low"


def subtitle_strategy(emotion: str, rhythm: str) -> str:
    if emotion == "awe":
        return "delayed-premium-subtitle"
    if rhythm == "slow-hold":
        return "minimal-subtitle"
    return "broadcast-lower-subtitle"


def decide(index: int, text: str, dna_principles: list[dict[str, Any]]) -> dict[str, Any]:
    emotion_scores = score_keywords(text, EMOTION_KEYWORDS)
    visual_scores = score_keywords(text, VISUAL_KEYWORDS)
    emotion = top_key(emotion_scores, "neutral-cinematic")
    visual = top_key(visual_scores, "establishing-wide")
    rhythm = rhythm_for_text(text)
    silence = silence_need(emotion, text)
    subtitle = subtitle_strategy(emotion, rhythm)

    decision = {
        "id": f"decision-{index:02d}",
        "narration": text,
        "emotion": emotion,
        "rhythm": rhythm,
        "visual_intention": visual,
        "shot_preference": visual,
        "silence_need": silence,
        "subtitle_strategy": subtitle,
        "reasoning": f"Narration suggests {emotion}; visual direction should favor {visual}; rhythm should be {rhythm}.",
    }
    return apply_adventure_dna(decision, dna_principles)


def build_markdown(title: str, decisions: list[dict[str, Any]]) -> str:
    content = f"# Director Decisions — {title}\n\n"
    content += "Generated by Director Intelligence v0.1 with Adventure DNA.\n\n"
    for decision in decisions:
        dna = decision.get("adventure_dna") or {}
        content += f"## {decision['id']}\n\n"
        content += f"**Narration:** {decision['narration']}\n\n"
        content += f"**Emotion:** {decision['emotion']}  \n"
        content += f"**Rhythm:** {decision['rhythm']}  \n"
        content += f"**Visual Intention:** {decision['visual_intention']}  \n"
        content += f"**Shot Preference:** {decision['shot_preference']}  \n"
        content += f"**Silence Need:** {decision['silence_need']}  \n"
        content += f"**Subtitle Strategy:** {decision['subtitle_strategy']}  \n"
        if dna:
            content += f"**Adventure DNA:** {dna.get('id')} — {dna.get('name')}  \n"
            content += f"**DNA Rule:** {dna.get('visual_rule')}  \n"
        content += f"**Reasoning:** {decision['reasoning']}\n\n---\n\n"
    return content


def main() -> None:
    args = parse_args()
    project_folder = Path(args.project_folder).expanduser().resolve()
    config = load_project_config(project_folder=str(project_folder))
    title = get_nested(config, "project.title", "Untitled Project")
    narration_lines = read_narration(config)
    dna_principles = load_adventure_dna()
    decisions = [decide(i, line, dna_principles) for i, line in enumerate(narration_lines, start=1)]

    data = {"schema": "turvis.director.decisions.v0.1", "project": {"title": title}, "decisions": decisions}
    (project_folder / "director-decisions.json").write_text(json.dumps(data, ensure_ascii=False, indent=2), encoding="utf-8")
    (project_folder / "director-decisions.md").write_text(build_markdown(title, decisions), encoding="utf-8")

    print(f"Created: {project_folder / 'director-decisions.json'}")
    print(f"Created: {project_folder / 'director-decisions.md'}")


if __name__ == "__main__":
    main()
