#!/usr/bin/env python3
"""
TURVIS Director Prep CLI v0.1

Creates a Director-ready prep package from project.yaml, narration.md, and director-handoff.md.

Local-first. No AI API calls.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parents[2]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from apps.common.project_config import get_nested, load_project_config  # noqa: E402


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Prepare Director package from project files")
    parser.add_argument("--project-folder", required=True, help="Project folder containing project.yaml")
    parser.add_argument("--output", default=None, help="Output director prep markdown path")
    return parser.parse_args()


def read_optional(path_value: str | None, fallback: str) -> str:
    if not path_value:
        return fallback
    path = Path(path_value).expanduser()
    if not path.exists():
        return fallback
    return path.read_text(encoding="utf-8")


def build_project_summary(config: dict[str, Any]) -> str:
    references = get_nested(config, "style.references", [])
    mood = get_nested(config, "style.mood", [])
    if not isinstance(references, list):
        references = [str(references)]
    if not isinstance(mood, list):
        mood = [str(mood)]

    return f"""## Project Summary

| Field | Value |
|---|---|
| Title | {get_nested(config, 'project.title', 'Untitled Project')} |
| ID | {get_nested(config, 'project.id', 'unknown')} |
| Type | {get_nested(config, 'project.type', 'unknown')} |
| Status | {get_nested(config, 'project.status', 'unknown')} |
| Aspect Ratio | {get_nested(config, 'output.aspect_ratio', 'unknown')} |
| Resolution | {get_nested(config, 'output.resolution', 'unknown')} |
| Target Duration | {get_nested(config, 'output.target_duration_seconds', 'unknown')} seconds |
| Language | {get_nested(config, 'output.language', 'unknown')} |
| Country | {get_nested(config, 'locations.country', 'unknown')} |
| Region | {get_nested(config, 'locations.region', 'unknown')} |
| Destination | {get_nested(config, 'locations.destination', 'unknown')} |
| Route | {get_nested(config, 'locations.route', 'unknown')} |

**Style References:** {', '.join(references)}  
**Mood:** {', '.join(mood)}
"""


def build_prep(config: dict[str, Any], narration: str, handoff: str) -> str:
    title = get_nested(config, "project.title", "Untitled Project")

    return f"""# Director Prep Package — {title}

Generated by `apps/director-prep/prepare_director.py`.

This file is the handoff from production preparation to the Documentary Director.

---

{build_project_summary(config)}

---

## Director Mission

Create a storyboard-first documentary plan.

Do not start with Remotion code.
Do not select clips randomly.
Use the narration and footage candidate pool to build emotional story beats.

Required output from the Documentary Director:

1. Project interpretation
2. Emotional arc
3. Narration segmentation
4. Story beat table
5. Shot selection plan
6. Subtitle plan
7. Timeline plan
8. Remotion implementation plan
9. QC checklist

---

## Narration

{narration}

---

## Footage Candidate Pool

{handoff}

---

## Director Rules

- Storyboard first.
- Timeline second.
- Remotion third.
- Quality control always.
- Nature is the main character unless the project spec says otherwise.
- Every selected clip must serve emotion or story.
- Avoid vlog-style editing.
- Keep subtitles premium and broadcast-style.
"""


def main() -> None:
    args = parse_args()
    config = load_project_config(project_folder=args.project_folder)

    narration_path = get_nested(config, "paths.narration")
    handoff_path = get_nested(config, "paths.director_handoff")
    output_path = Path(args.output).expanduser().resolve() if args.output else Path(args.project_folder).expanduser().resolve() / "director-prep.md"

    narration = read_optional(narration_path, "Narration file not found or not configured.")
    handoff = read_optional(handoff_path, "Director handoff file not found or not configured.")

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(build_prep(config, narration, handoff), encoding="utf-8")
    print(f"Director prep package created: {output_path}")


if __name__ == "__main__":
    main()
