#!/usr/bin/env python3
"""
TURVIS Director Handoff CLI v0.1

Builds a Director-ready handoff package from Adventure Memory JSON files.

Local-first. No AI API calls.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

DEFAULT_STORY_BUCKETS = [
    "opening",
    "establishing",
    "threshold",
    "journey",
    "preparation",
    "discovery",
    "texture",
    "scale",
    "arrival",
    "camp",
    "reflection",
    "ending",
]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Generate a TURVIS Director handoff package")
    parser.add_argument("--memory", required=True, help="Folder containing footage memory JSON files")
    parser.add_argument("--project", required=True, help="Project name for the handoff")
    parser.add_argument("--output", default=None, help="Output markdown path")
    parser.add_argument("--min-score", type=int, default=0, help="Minimum overall score")
    parser.add_argument("--exclude-avoid", action="store_true", help="Exclude clips marked avoid")
    parser.add_argument("--include-review", action="store_true", help="Include clips still marked needs_review")
    parser.add_argument("--per-bucket", type=int, default=5, help="Maximum clips per story bucket")
    return parser.parse_args()


def load_records(memory_dir: Path) -> list[dict[str, Any]]:
    records: list[dict[str, Any]] = []
    for path in sorted(memory_dir.glob("*.json")):
        try:
            record = json.loads(path.read_text(encoding="utf-8"))
            record["_json_path"] = str(path)
            records.append(record)
        except json.JSONDecodeError:
            continue
    return records


def is_eligible(record: dict[str, Any], args: argparse.Namespace) -> bool:
    scores = record.get("scores") or {}
    flags = record.get("flags") or {}

    if args.exclude_avoid and flags.get("avoid", False):
        return False

    if not args.include_review and flags.get("needs_review", False):
        return False

    if int(scores.get("overall") or 0) < args.min_score:
        return False

    return True


def rank_record(record: dict[str, Any]) -> int:
    scores = record.get("scores") or {}
    flags = record.get("flags") or {}
    score = int(scores.get("overall") or 0)

    if flags.get("hero_shot"):
        score += 20
    if flags.get("needs_review"):
        score -= 10
    if flags.get("avoid"):
        score -= 100

    return score


def bucket_records(records: list[dict[str, Any]], args: argparse.Namespace) -> dict[str, list[dict[str, Any]]]:
    buckets: dict[str, list[dict[str, Any]]] = {bucket: [] for bucket in DEFAULT_STORY_BUCKETS}

    for record in records:
        if not is_eligible(record, args):
            continue
        story_tags = [str(tag).lower() for tag in record.get("story_tags", [])]
        best_usage = [str(tag).lower() for tag in record.get("best_usage", [])]
        combined = set(story_tags + best_usage)

        for bucket in DEFAULT_STORY_BUCKETS:
            if bucket in combined:
                buckets[bucket].append(record)

    for bucket in buckets:
        buckets[bucket].sort(key=rank_record, reverse=True)
        buckets[bucket] = buckets[bucket][: args.per_bucket]

    return buckets


def format_clip(record: dict[str, Any]) -> str:
    flags = record.get("flags") or {}
    scores = record.get("scores") or {}
    camera = record.get("camera") or {}
    location = record.get("location") or {}
    keyframes = record.get("keyframes") or {}

    return f"""- **{record.get('clip_id', 'unknown')}** — `{record.get('original_filename', 'unknown')}`
  - Asset: `{record.get('asset_path', 'unknown')}`
  - Location: {location.get('name', 'unknown')} / {location.get('sub_location', 'unknown')}
  - Shot: {camera.get('shot_type', 'unknown')} / {camera.get('movement', 'unknown')}
  - Emotion: {', '.join(record.get('emotion_tags', []))}
  - Story: {', '.join(record.get('story_tags', []))}
  - Best usage: {', '.join(record.get('best_usage', []))}
  - Score: {scores.get('overall', 0)} | Hero: {flags.get('hero_shot', False)} | Needs review: {flags.get('needs_review', False)}
  - Keyframes: `{keyframes.get('folder', '')}`
  - Notes: {record.get('director_notes', '')}
"""


def build_handoff(project: str, records: list[dict[str, Any]], buckets: dict[str, list[dict[str, Any]]], args: argparse.Namespace) -> str:
    eligible_count = sum(1 for record in records if is_eligible(record, args))
    hero_count = sum(1 for record in records if (record.get("flags") or {}).get("hero_shot"))
    review_count = sum(1 for record in records if (record.get("flags") or {}).get("needs_review"))

    content = f"""# Director Handoff — {project}

Generated by `apps/footage-analyzer/director_handoff.py`.

## Summary

| Category | Count |
|---|---:|
| Total memory records | {len(records)} |
| Eligible records | {eligible_count} |
| Hero shots | {hero_count} |
| Needs review | {review_count} |

## Director Instructions

Use this handoff as the footage candidate pool.

Do not treat this as a final edit.
Use it to build the story beat table, storyboard, and timeline.

Priority order:

1. Emotion
2. Story relevance
3. Landscape power
4. Shot quality
5. Pacing
6. Technical stability

---

"""

    for bucket, bucket_records_list in buckets.items():
        content += f"## {bucket.title()} Candidates\n\n"
        if not bucket_records_list:
            content += "No candidates found.\n\n---\n\n"
            continue
        for record in bucket_records_list:
            content += format_clip(record) + "\n"
        content += "---\n\n"

    content += """## Next Step

The Documentary Director should now:

1. Read the project brief.
2. Read this handoff.
3. Create a story beat table.
4. Select the strongest candidate clips for each beat.
5. Build a storyboard.
6. Convert the storyboard into a Remotion timeline.
"""

    return content


def main() -> None:
    args = parse_args()
    memory_dir = Path(args.memory).expanduser().resolve()
    if not memory_dir.exists():
        raise FileNotFoundError(f"Memory folder does not exist: {memory_dir}")

    output_path = (
        Path(args.output).expanduser().resolve()
        if args.output
        else memory_dir / "director-handoff.md"
    )

    records = load_records(memory_dir)
    buckets = bucket_records(records, args)
    output = build_handoff(args.project, records, buckets, args)
    output_path.write_text(output, encoding="utf-8")
    print(f"Director handoff created: {output_path}")


if __name__ == "__main__":
    main()
