#!/usr/bin/env python3
"""
TURVIS Review Queue Generator v0.1

Builds a human/AI review queue from Adventure Memory JSON files.

Local-first. No AI API calls.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Generate TURVIS footage review queue")
    parser.add_argument("--memory", required=True, help="Folder containing footage memory JSON files")
    parser.add_argument("--output", default=None, help="Output review queue markdown path")
    parser.add_argument("--include-reviewed", action="store_true", help="Include clips even if needs_review is false")
    return parser.parse_args()


def load_json_files(memory_dir: Path) -> list[dict[str, Any]]:
    records = []
    for path in sorted(memory_dir.glob("*.json")):
        try:
            records.append(json.loads(path.read_text(encoding="utf-8")))
        except json.JSONDecodeError:
            continue
    return records


def should_include(record: dict[str, Any], include_reviewed: bool) -> bool:
    if include_reviewed:
        return True
    flags = record.get("flags") or {}
    return bool(flags.get("needs_review", True))


def format_record(record: dict[str, Any]) -> str:
    clip_id = record.get("clip_id", "unknown")
    filename = record.get("original_filename", "unknown")
    asset_path = record.get("asset_path", "unknown")
    keyframes = record.get("keyframes") or {}
    keyframe_folder = keyframes.get("folder", "")
    keyframe_list = keyframes.get("frames", [])
    scores = record.get("scores") or {}
    flags = record.get("flags") or {}

    keyframe_lines = "\n".join([f"  - `{frame}`" for frame in keyframe_list]) or "  - No keyframes available"

    return f"""## {clip_id}

**Filename:** `{filename}`  
**Asset Path:** `{asset_path}`  
**Overall Score:** {scores.get('overall', 0)}  
**Needs Review:** {flags.get('needs_review', True)}  
**Avoid:** {flags.get('avoid', False)}  
**Hero Shot:** {flags.get('hero_shot', False)}  

**Keyframe Folder:** `{keyframe_folder}`

**Keyframes:**
{keyframe_lines}

**Review Prompt:** `prompts/keyframe-review-prompt-v0.1.md`

**Reviewer Notes:**

```text
Fill after review.
```

---
"""


def write_review_queue(records: list[dict[str, Any]], output_path: Path, include_reviewed: bool) -> None:
    included = [r for r in records if should_include(r, include_reviewed)]

    content = f"""# TURVIS Footage Review Queue

Generated by `apps/footage-analyzer/review_queue.py`.

## Summary

| Category | Count |
|---|---:|
| Total memory records | {len(records)} |
| Clips in review queue | {len(included)} |

---

## Review Instructions

For each clip below:

1. Open the keyframes.
2. Use `prompts/keyframe-review-prompt-v0.1.md`.
3. Update the matching `.md` and `.json` memory files.
4. Set `needs_review` to false only when confident.

---

"""

    for record in included:
        content += format_record(record)

    output_path.write_text(content, encoding="utf-8")


def main() -> None:
    args = parse_args()
    memory_dir = Path(args.memory).expanduser().resolve()
    if not memory_dir.exists():
        raise FileNotFoundError(f"Memory folder does not exist: {memory_dir}")

    output_path = Path(args.output).expanduser().resolve() if args.output else memory_dir / "review-queue.md"
    records = load_json_files(memory_dir)
    write_review_queue(records, output_path, args.include_reviewed)
    print(f"Review queue created: {output_path}")


if __name__ == "__main__":
    main()
